### ISSUE TITLE
tile placing features

### ISSUE THREAD

**Issue by derrick56007** [ppvk/libpen#7]
It would be cool if this library implemented different way to place tiles in a 2d array. The console class could either implement a method that renders a 2d array at a certain point on the console

``` Dart
void put2DArrayAt(2DArray array, int offsetX, int offsetY) {...}
```

or render only a portion of the 2d array.

I already have a pretty solid implementation of the [camera class](https://github.com/Derrick56007/DartRogueV2/blob/master/lib/src/rogue_map/camera.dart) and you can see how it is used [here](https://github.com/Derrick56007/DartRogueV2/blob/master/web/main.dart). A way I see this being useful is if you have different 2d arrays of things such as the map, player stats, or a menu to choose items. This way you can overlap the arrays without losing data.

**Comment by derrick56007** [comment]
Ignore the use of unicodetiles.js over libpen; this can be implemented in any of the libraries (including StageXL)

**Comment by ppvk** [comment]
I was looking at your camera yesterday, and It led me to implement [this](https://github.com/ppvk/libpen/blob/dev/lib/src/core/image.dart#L15-L31). The Image class will do what I think you want. You can then 'draw' the Image to the Console, or another Image using [this](https://github.com/ppvk/libpen/blob/dev/lib/src/core/image.dart#L88-L104).

I've also started taking it a step further with the Field class. in the new gui.dart file on the dev branch. You can see an example of this [here](https://github.com/ppvk/libpen/blob/dev/test/test_draw.dart#L10-L38). With Fields you can define scrolling text areas, minimaps, and play areas. I'm putting this sort of thing in a separate bundled library so the user can choose whether or not they want out windowing system.

Let me know what you think.

**Comment by ppvk** [comment]
I'll close this for now. If the Image class doesn't work for you, then I'll reopen.

**Comment by derrick56007** [comment]
Looks good! :+1:
